
package model;

public enum BankService {
    CREATE_ACCOUNT,
    CREATE_INVESTMENT,
    MAKE_INVESTMENT,
    DEPOSIT,
    WITHDRAW,
    TRANSFER,
    INVEST,
    WITHDRAW_INVESTMENT,
    LIST_ACCOUNTS,
    LIST_INVESTMENTS,
    LIST_WALLETS,
    UPDATE_INVESTMENTS,
    ACCOUNT_HISTORY,
    EXIT
}
